package com.medibridge.core.model;

import jakarta.persistence.*;
import lombok.*;

/**
 * JPA Entity representing the clinical record generated by a doctor after an appointment.
 */
@Entity
@Table(name = "consultation_record")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ConsultationRecord {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "consultation_id")
    private Integer consultationId;

    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "appointment_id", nullable = false, unique = true)
    private Appointment appointment;

    @Column(name = "diagnosis", nullable = false, length = 255)
    private String diagnosis;

    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    @Column(name = "has_prescription")
    @Builder.Default
    private Boolean hasPrescription = false;
}
